Fix Deprecating static attributes in factory_bot
ref: [Deprecating static attributes in factory_bot 4.11](https://thoughtbot.com/blog/deprecating-static-attributes-in-factory_bot-4-11)

```
$ rspec ./spec/environment_spec.rb:22 # SeedDump.dump_using_environment APPEND should specify append as true if the APPEND env var is 'TRUE'

An error occurred while loading ./spec/environment_spec.rb.
Failure/Error: string   'string'

NoMethodError:
  undefined method 'string' in 'another_sample' factory
  Did you mean? 'string { "string" }'
Run options: include {:locations=>{"./spec/environment_spec.rb"=>[22]}}

All examples were filtered out

Finished in 0.00004 seconds (files took 1.18 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

Fix by

```
$ rubocop -a --require rubocop-rspec --only FactoryBot/AttributeDefinedStatically
```

thank you